{{/*# Copyright 2019, Oracle Corporation and/or its affiliates.  All rights reserved.*/}}
{{/*# Licensed under the Universal Permissive License v 1.0 as shown at*/}}
{{/*# http://oss.oracle.com/licenses/upl.*/}}
{{/* */}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "coherence.fullname" . }}-pdb
  labels:
    {{- include "coherence.release_labels" . | indent 4 }}
    component: "coherence-pdb"
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      coherenceDeployment: {{ template "coherence.fullname" . }}
      coherenceCluster: {{ template "coherence.clusterName" . }}
      coherenceRole: {{ template "coherence.role" . }}
