{{/* Copyright 2019, Oracle Corporation and/or its affiliates.  All rights reserved. */}}
{{/* Licensed under the Universal Permissive License v 1.0 as shown at               */}}
{{/* http://oss.oracle.com/licenses/upl.                                             */}}

{{- if .Values.logCaptureEnabled }}
  {{- if not .Values.elasticsearchEndpoint.host }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
{{- include "coherence-operator.release_labels" . | indent 4 }}
    component: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      coherenceOperatorCluster: {{ template "coherence-operator.fullname" . }}
      component: elasticsearch
  template:
    metadata:
      labels:
        coherenceOperatorCluster: {{ template "coherence-operator.fullname" . }}
        app: {{ template "coherence-operator.name" . }}
        release: {{ .Release.Name }}
        component: elasticsearch
    spec:
{{- if .Values.imagePullSecrets }}
  {{- $secretsType := typeOf .Values.imagePullSecrets }}
      imagePullSecrets:
  {{- if eq $secretsType "string" }}
      - name: {{ .Values.imagePullSecrets }}
  {{- else }}
    {{- range .Values.imagePullSecrets }}
      - name: {{ . }}
    {{- end }}
  {{- end }}
{{- end }}
      containers:
        - name: elasticsearch
          image: {{ .Values.elasticsearch.image }}
          imagePullPolicy: {{ .Values.elasticsearch.imagePullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: 9200
            - containerPort: 9300
---
kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
  labels:
{{- include "coherence-operator.release_labels" . | indent 4 }}
    component: elasticsearch-service
spec:
  ports:
    - name: http
      protocol: TCP
      port: 9200
      targetPort: 9200
    - name: https
      protocol: TCP
      port: 9300
      targetPort: 9300
  selector:
    coherenceOperatorCluster: {{ template "coherence-operator.fullname" . }}
    component: elasticsearch
  {{- end }}
{{- end }}
