apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: coherence-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - namespaces
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - coherence-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - coherence.oracle.com
  resources:
  - '*'
  verbs:
  - '*'
