apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  cacheConfig: test-config.xml
  roles:
    - role: data
    - role: proxy
      cacheConfig: proxy-config.xml
