apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  logging:
    fluentd:
      enabled: true
      imagePullPolicy: Never
  roles:
    - role: data
    - role: proxy
      logging:
        fluentd:
          imagePullPolicy: Always
