apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  logging:
    configMapName: cm-default-logging
  roles:
    - role: data
      logging:
        configMapName: cm-logging
    - role: proxy
