apiVersion: apps/v1
kind: Deployment
metadata:
  name: coherence-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: coherence-operator
  template:
    metadata:
      labels:
        name: coherence-operator
    spec:
      serviceAccountName: coherence-operator
      containers:
        - name: coherence-operator
          # Replace this with the built image name
          image: iad.ocir.io/odx-stateservice/test/oracle/coherence-operator:2.0.0-SNAPSHOT
          imagePullPolicy: Never
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "coherence-operator"
