apiVersion: v1
entries:
  coherence:
  - apiVersion: v1
    appVersion: 0.9.5
    created: 2019-05-28T18:10:55.801509961Z
    description: Coherence in Kubernetes
    digest: 5a78941e77c93fa3d77ccc50197555005aeb1d987e93afd0448b52dab8ffbe50
    home: https://github.com/oracle/coherence-operator
    icon: https://docs.oracle.com/en/dcommon/img/oracle-doc-logo.png
    keywords:
    - coherence
    name: coherence
    sources:
    - https://github.com/oracle/coherence-operator
    urls:
    - https://oracle.github.io/coherence-operator/charts/coherence-0.9.5.tgz
    version: 0.9.5
  - apiVersion: v1
    appVersion: 0.9.4
    created: 2019-05-28T18:10:55.800265809Z
    description: Coherence in Kubernetes
    digest: e8077830cd6c3ac39e93897035c76d978a27cdd6beda1440705224c3ffeb4492
    home: https://github.com/oracle/coherence-operator
    icon: https://docs.oracle.com/en/dcommon/img/oracle-doc-logo.png
    keywords:
    - coherence
    name: coherence
    sources:
    - https://github.com/oracle/coherence-operator
    urls:
    - https://oracle.github.io/coherence-operator/charts/coherence-0.9.4.tgz
    version: 0.9.4
  - apiVersion: v1
    appVersion: 0.9.3
    created: 2019-05-28T18:10:55.798870304Z
    description: Coherence in Kubernetes
    digest: 23d32f064de903205c55290be7d5f493104d0c76dbbe3f270b926867e4b30e74
    home: https://github.com/oracle/coherence-operator
    icon: https://docs.oracle.com/en/dcommon/img/oracle-doc-logo.png
    keywords:
    - coherence
    name: coherence
    sources:
    - https://github.com/oracle/coherence-operator
    urls:
    - https://oracle.github.io/coherence-operator/charts/coherence-0.9.3.tgz
    version: 0.9.3
  coherence-operator:
  - apiVersion: v1
    appVersion: 0.9.5
    created: 2019-05-28T18:10:55.835540895Z
    description: A Kubernetes Operator for Coherence
    digest: 438edb4ee1b2def3695ce636d44ab0fbdae032555018716768dfc36ea04deec8
    home: https://github.com/oracle/coherence-operator
    icon: https://docs.oracle.com/en/dcommon/img/oracle-doc-logo.png
    keywords:
    - operator
    - coherence
    - datagrid
    name: coherence-operator
    sources:
    - https://github.com/oracle/coherence-operator
    urls:
    - https://oracle.github.io/coherence-operator/charts/coherence-operator-0.9.5.tgz
    version: 0.9.5
  - apiVersion: v1
    appVersion: 0.9.4
    created: 2019-05-28T18:10:55.825522005Z
    description: A Kubernetes Operator for Coherence
    digest: 9696b0cccd098f362313955b25a91aa22465672e9d28b1c577e7f18cb97c3895
    home: https://github.com/oracle/coherence-operator
    icon: https://docs.oracle.com/en/dcommon/img/oracle-doc-logo.png
    keywords:
    - operator
    - coherence
    - datagrid
    name: coherence-operator
    sources:
    - https://github.com/oracle/coherence-operator
    urls:
    - https://oracle.github.io/coherence-operator/charts/coherence-operator-0.9.4.tgz
    version: 0.9.4
  - apiVersion: v1
    appVersion: 0.9.3
    created: 2019-05-28T18:10:55.812698437Z
    description: A Kubernetes Operator for Coherence
    digest: 4ffe57a7f81974baa4ae1cc6d0485747f266d99d1af17e73a283c4b73c6a5b3a
    home: https://github.com/oracle/coherence-operator
    icon: https://docs.oracle.com/en/dcommon/img/oracle-doc-logo.png
    keywords:
    - operator
    - coherence
    - datagrid
    name: coherence-operator
    sources:
    - https://github.com/oracle/coherence-operator
    urls:
    - https://oracle.github.io/coherence-operator/charts/coherence-operator-0.9.3.tgz
    version: 0.9.3
generated: 2019-05-28T18:10:55.797638489Z
