apiVersion: v1
entries:
  coherence-operator:
  - apiVersion: v1
    appVersion: 3.1.3
    created: "2021-01-28T14:22:43.49247865Z"
    description: A Kubernetes Operator for Coherence
    digest: 2ec55a9eadfc1507b4ab0183407128dee576573c68f7845ea8cc798fd6965914
    home: https://github.com/oracle/coherence-operator
    icon: https://docs.oracle.com/en/dcommon/img/oracle-doc-logo.png
    name: coherence-operator
    sources:
    - https://github.com/oracle/coherence-operator
    urls:
    - https://oracle.github.io/coherence-operator/charts/coherence-operator-3.1.3.tgz
    version: 3.1.3
  - apiVersion: v1
    appVersion: 3.1.2
    created: "2021-01-28T14:22:43.491553234Z"
    description: A Kubernetes Operator for Coherence
    digest: 92d90ae08a7c97d0555abbd43dd9e3b59378f193117e27c07f70a3ef14a4cf29
    home: https://github.com/oracle/coherence-operator
    icon: https://docs.oracle.com/en/dcommon/img/oracle-doc-logo.png
    name: coherence-operator
    sources:
    - https://github.com/oracle/coherence-operator
    urls:
    - https://oracle.github.io/coherence-operator/charts/coherence-operator-3.1.2.tgz
    version: 3.1.2
  - apiVersion: v1
    appVersion: 3.1.1
    created: "2021-01-28T14:22:43.491123227Z"
    description: A Kubernetes Operator for Coherence
    digest: 795f65f6b294aba2b13839dd6b0c1a22f74d025a5674932228d0eb0b5c5d5d2c
    home: https://github.com/oracle/coherence-operator
    icon: https://docs.oracle.com/en/dcommon/img/oracle-doc-logo.png
    name: coherence-operator
    sources:
    - https://github.com/oracle/coherence-operator
    urls:
    - https://oracle.github.io/coherence-operator/charts/coherence-operator-3.1.1.tgz
    version: 3.1.1
  - apiVersion: v1
    appVersion: 3.1.0
    created: "2021-01-28T14:22:43.49071842Z"
    description: A Kubernetes Operator for Coherence
    digest: 8a2907c0c019f5c42053422361bdaf606a74ab544720c4d376a0ae60d011720c
    home: https://github.com/oracle/coherence-operator
    icon: https://docs.oracle.com/en/dcommon/img/oracle-doc-logo.png
    name: coherence-operator
    sources:
    - https://github.com/oracle/coherence-operator
    urls:
    - https://oracle.github.io/coherence-operator/charts/coherence-operator-3.1.0.tgz
    version: 3.1.0
  - apiVersion: v1
    appVersion: 3.0.2
    created: "2021-01-28T14:22:43.490308113Z"
    description: A Kubernetes Operator for Coherence
    digest: fc436c601886c71145b56cdb04f64326827562bd551b51328a53f491a1bfda3e
    home: https://github.com/oracle/coherence-operator
    icon: https://docs.oracle.com/en/dcommon/img/oracle-doc-logo.png
    name: coherence-operator
    sources:
    - https://github.com/oracle/coherence-operator
    urls:
    - https://oracle.github.io/coherence-operator/charts/coherence-operator-3.0.2.tgz
    version: 3.0.2
  - apiVersion: v1
    appVersion: 3.0.1
    created: "2021-01-28T14:22:43.489927207Z"
    description: A Kubernetes Operator for Coherence
    digest: b150c3a565178a5736d1b29f1c43e0a19106160f275166d21eee2eb48df2e67b
    home: https://github.com/oracle/coherence-operator
    icon: https://docs.oracle.com/en/dcommon/img/oracle-doc-logo.png
    name: coherence-operator
    sources:
    - https://github.com/oracle/coherence-operator
    urls:
    - https://oracle.github.io/coherence-operator/charts/coherence-operator-3.0.1.tgz
    version: 3.0.1
  - apiVersion: v1
    appVersion: 3.0.0
    created: "2021-01-28T14:22:43.4895332Z"
    description: A Kubernetes Operator for Coherence
    digest: 9acd77ebb7e0fbfe720a6f24885c546ea2306dd96f0c0f4a93eab8454167983f
    home: https://github.com/oracle/coherence-operator
    icon: https://docs.oracle.com/en/dcommon/img/oracle-doc-logo.png
    name: coherence-operator
    sources:
    - https://github.com/oracle/coherence-operator
    urls:
    - https://oracle.github.io/coherence-operator/charts/coherence-operator-3.0.0.tgz
    version: 3.0.0
  - apiVersion: v1
    appVersion: 2.1.1
    created: "2021-01-28T14:22:43.489115893Z"
    dependencies:
    - alias: prometheusoperator
      condition: prometheusoperator.enabled
      name: prometheus-operator
      repository: https://kubernetes-charts.storage.googleapis.com/
      version: 5.7.0
    description: A Kubernetes Operator for Coherence
    digest: be8f837e34b4bce090b4ccdf97b31a39ae47b714a13fcadcfeff4c26f9a81329
    home: https://github.com/oracle/coherence-operator
    icon: https://docs.oracle.com/en/dcommon/img/oracle-doc-logo.png
    name: coherence-operator
    sources:
    - https://github.com/oracle/coherence-operator
    urls:
    - https://oracle.github.io/coherence-operator/charts/coherence-operator-2.1.1.tgz
    version: 2.1.1
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2021-01-28T14:22:43.472735213Z"
    dependencies:
    - alias: prometheusoperator
      condition: prometheusoperator.enabled
      name: prometheus-operator
      repository: https://kubernetes-charts.storage.googleapis.com/
      version: 5.7.0
    description: A Kubernetes Operator for Coherence
    digest: 58e1c47a902a4f044cdc2d1ca4343ea653ab73ec113157dfc845825b34506ccd
    home: https://github.com/oracle/coherence-operator
    icon: https://docs.oracle.com/en/dcommon/img/oracle-doc-logo.png
    name: coherence-operator
    sources:
    - https://github.com/oracle/coherence-operator
    urls:
    - https://oracle.github.io/coherence-operator/charts/coherence-operator-2.1.0.tgz
    version: 2.1.0
  - apiVersion: v1
    appVersion: 2.0.5
    created: "2021-01-28T14:22:43.456382534Z"
    dependencies:
    - alias: prometheusoperator
      condition: prometheusoperator.enabled
      name: prometheus-operator
      repository: https://kubernetes-charts.storage.googleapis.com/
      version: 5.7.0
    description: A Kubernetes Operator for Coherence
    digest: 818c19ec13489c1d12f75a98179e8a091866cc4d2299ebd669dab62362d2e876
    home: https://github.com/oracle/coherence-operator
    icon: https://docs.oracle.com/en/dcommon/img/oracle-doc-logo.png
    name: coherence-operator
    sources:
    - https://github.com/oracle/coherence-operator
    urls:
    - https://oracle.github.io/coherence-operator/charts/coherence-operator-2.0.5.tgz
    version: 2.0.5
  - apiVersion: v1
    appVersion: 2.0.4
    created: "2021-01-28T14:22:43.437991421Z"
    dependencies:
    - alias: prometheusoperator
      condition: prometheusoperator.enabled
      name: prometheus-operator
      repository: https://kubernetes-charts.storage.googleapis.com/
      version: 5.7.0
    description: A Kubernetes Operator for Coherence
    digest: 06004b22a978bb241c56b736749b21b86e604c0e6c829a688d17328140f6ef0e
    home: https://github.com/oracle/coherence-operator
    icon: https://docs.oracle.com/en/dcommon/img/oracle-doc-logo.png
    name: coherence-operator
    sources:
    - https://github.com/oracle/coherence-operator
    urls:
    - https://oracle.github.io/coherence-operator/charts/coherence-operator-2.0.4.tgz
    version: 2.0.4
  - apiVersion: v1
    appVersion: 2.0.3
    created: "2021-01-28T14:22:43.368058428Z"
    dependencies:
    - alias: prometheusoperator
      condition: prometheusoperator.enabled
      name: prometheus-operator
      repository: https://kubernetes-charts.storage.googleapis.com/
      version: 5.7.0
    description: A Kubernetes Operator for Coherence
    digest: b92642289635fb6a5ff6481e311fae799647d79c46aa7a18d3164b7ccbe28786
    home: https://github.com/oracle/coherence-operator
    icon: https://docs.oracle.com/en/dcommon/img/oracle-doc-logo.png
    name: coherence-operator
    sources:
    - https://github.com/oracle/coherence-operator
    urls:
    - https://oracle.github.io/coherence-operator/charts/coherence-operator-2.0.3.tgz
    version: 2.0.3
generated: "2021-01-28T14:22:43.252785162Z"
