apiVersion: v1
entries:
  coherence:
  - apiVersion: v1
    appVersion: 1.0.0
    created: 2019-11-13T05:16:25.729442379Z
    description: Coherence in Kubernetes
    digest: d3e3b9aaf121b055955ca36e16810ee2dfdf45eef0e502448754f6eae465e8f4
    home: https://github.com/oracle/coherence-operator
    icon: https://docs.oracle.com/en/dcommon/img/oracle-doc-logo.png
    name: coherence
    sources:
    - https://github.com/oracle/coherence-operator
    urls:
    - https://oracle.github.io/coherence-operator/charts/coherence-1.0.0.tgz
    version: 1.0.0
  - apiVersion: v1
    appVersion: 0.9.10
    created: 2019-11-13T05:16:25.715960859Z
    description: Coherence in Kubernetes
    digest: 6790f6152aa591f099f5b50176f28114eeb3d9cf6a1c0b3fb14a5427a4affd09
    home: https://github.com/oracle/coherence-operator
    icon: https://docs.oracle.com/en/dcommon/img/oracle-doc-logo.png
    name: coherence
    sources:
    - https://github.com/oracle/coherence-operator
    urls:
    - https://oracle.github.io/coherence-operator/charts/coherence-0.9.10.tgz
    version: 0.9.10
  - apiVersion: v1
    appVersion: 0.9.9
    created: 2019-11-13T05:16:25.728100272Z
    description: Coherence in Kubernetes
    digest: d5b0f2d10fac3db560ccfda1ff663e74ac9895e27116f8413e861e3c3af5c787
    home: https://github.com/oracle/coherence-operator
    icon: https://docs.oracle.com/en/dcommon/img/oracle-doc-logo.png
    name: coherence
    sources:
    - https://github.com/oracle/coherence-operator
    urls:
    - https://oracle.github.io/coherence-operator/charts/coherence-0.9.9.tgz
    version: 0.9.9
  - apiVersion: v1
    appVersion: 0.9.8
    created: 2019-11-13T05:16:25.726731844Z
    description: Coherence in Kubernetes
    digest: 62325085def66b4d03877ffc405317945f0e9688f0c5ed9d7bc337583d3f38da
    home: https://github.com/oracle/coherence-operator
    icon: https://docs.oracle.com/en/dcommon/img/oracle-doc-logo.png
    name: coherence
    sources:
    - https://github.com/oracle/coherence-operator
    urls:
    - https://oracle.github.io/coherence-operator/charts/coherence-0.9.8.tgz
    version: 0.9.8
  - apiVersion: v1
    appVersion: 0.9.7
    created: 2019-11-13T05:16:25.724641423Z
    description: Coherence in Kubernetes
    digest: e7ef1d1eaf7a60df748fb4285db38855f8c9758ad629de7d9df054c47e94f97e
    home: https://github.com/oracle/coherence-operator
    icon: https://docs.oracle.com/en/dcommon/img/oracle-doc-logo.png
    keywords:
    - coherence
    name: coherence
    sources:
    - https://github.com/oracle/coherence-operator
    urls:
    - https://oracle.github.io/coherence-operator/charts/coherence-0.9.7.tgz
    version: 0.9.7
  - apiVersion: v1
    appVersion: 0.9.6
    created: 2019-11-13T05:16:25.721846908Z
    description: Coherence in Kubernetes
    digest: 30ab3f444c9b59c2f90794ab0171ff60c1268cc4595ca5ac785aefffb4d50b8b
    home: https://github.com/oracle/coherence-operator
    icon: https://docs.oracle.com/en/dcommon/img/oracle-doc-logo.png
    keywords:
    - coherence
    name: coherence
    sources:
    - https://github.com/oracle/coherence-operator
    urls:
    - https://oracle.github.io/coherence-operator/charts/coherence-0.9.6.tgz
    version: 0.9.6
  - apiVersion: v1
    appVersion: 0.9.5
    created: 2019-11-13T05:16:25.720212516Z
    description: Coherence in Kubernetes
    digest: 5a78941e77c93fa3d77ccc50197555005aeb1d987e93afd0448b52dab8ffbe50
    home: https://github.com/oracle/coherence-operator
    icon: https://docs.oracle.com/en/dcommon/img/oracle-doc-logo.png
    keywords:
    - coherence
    name: coherence
    sources:
    - https://github.com/oracle/coherence-operator
    urls:
    - https://oracle.github.io/coherence-operator/charts/coherence-0.9.5.tgz
    version: 0.9.5
  - apiVersion: v1
    appVersion: 0.9.4
    created: 2019-11-13T05:16:25.71879747Z
    description: Coherence in Kubernetes
    digest: e8077830cd6c3ac39e93897035c76d978a27cdd6beda1440705224c3ffeb4492
    home: https://github.com/oracle/coherence-operator
    icon: https://docs.oracle.com/en/dcommon/img/oracle-doc-logo.png
    keywords:
    - coherence
    name: coherence
    sources:
    - https://github.com/oracle/coherence-operator
    urls:
    - https://oracle.github.io/coherence-operator/charts/coherence-0.9.4.tgz
    version: 0.9.4
  - apiVersion: v1
    appVersion: 0.9.3
    created: 2019-11-13T05:16:25.717332588Z
    description: Coherence in Kubernetes
    digest: 23d32f064de903205c55290be7d5f493104d0c76dbbe3f270b926867e4b30e74
    home: https://github.com/oracle/coherence-operator
    icon: https://docs.oracle.com/en/dcommon/img/oracle-doc-logo.png
    keywords:
    - coherence
    name: coherence
    sources:
    - https://github.com/oracle/coherence-operator
    urls:
    - https://oracle.github.io/coherence-operator/charts/coherence-0.9.3.tgz
    version: 0.9.3
  coherence-operator:
  - apiVersion: v1
    appVersion: 2.0.1
    created: 2019-11-13T05:16:25.877995305Z
    description: A Kubernetes Operator for Coherence
    digest: 0dd7e5a038437c59757f93eab02602b13fdd80f627a7a6a1d4f767c4207f5b3a
    home: https://github.com/oracle/coherence-operator
    icon: https://docs.oracle.com/en/dcommon/img/oracle-doc-logo.png
    name: coherence-operator
    sources:
    - https://github.com/oracle/coherence-operator
    urls:
    - https://oracle.github.io/coherence-operator/charts/coherence-operator-2.0.1.tgz
    version: 2.0.1
  - apiVersion: v1
    appVersion: 2.0.0
    created: 2019-11-13T05:16:25.864518044Z
    description: A Kubernetes Operator for Coherence
    digest: 82549ae4b65b45b6c59a7880fbd1cf06a24a2c5178a60388eb0790215c6c2401
    home: https://github.com/oracle/coherence-operator
    icon: https://docs.oracle.com/en/dcommon/img/oracle-doc-logo.png
    name: coherence-operator
    sources:
    - https://github.com/oracle/coherence-operator
    urls:
    - https://oracle.github.io/coherence-operator/charts/coherence-operator-2.0.0.tgz
    version: 2.0.0
  - apiVersion: v1
    appVersion: 1.0.0
    created: 2019-11-13T05:16:25.851029126Z
    description: A Kubernetes Operator for Coherence
    digest: 822f381e0cadad9846ae26a524ddc54d2a8d71bfd340baab51257935ce2604ea
    home: https://github.com/oracle/coherence-operator
    icon: https://docs.oracle.com/en/dcommon/img/oracle-doc-logo.png
    name: coherence-operator
    sources:
    - https://github.com/oracle/coherence-operator
    urls:
    - https://oracle.github.io/coherence-operator/charts/coherence-operator-1.0.0.tgz
    version: 1.0.0
  - apiVersion: v1
    appVersion: 0.9.10
    created: 2019-11-13T05:16:25.745565422Z
    description: A Kubernetes Operator for Coherence
    digest: c6b094de80488d72ee4208cac0a492810127deb5b791a06a79fba2315b8400de
    home: https://github.com/oracle/coherence-operator
    icon: https://docs.oracle.com/en/dcommon/img/oracle-doc-logo.png
    name: coherence-operator
    sources:
    - https://github.com/oracle/coherence-operator
    urls:
    - https://oracle.github.io/coherence-operator/charts/coherence-operator-0.9.10.tgz
    version: 0.9.10
  - apiVersion: v1
    appVersion: 0.9.9
    created: 2019-11-13T05:16:25.837402914Z
    description: A Kubernetes Operator for Coherence
    digest: fd955cd4726252b3001ceb6c9e1e3a38bba969e5216c4e4de019b92d8ec5f75c
    home: https://github.com/oracle/coherence-operator
    icon: https://docs.oracle.com/en/dcommon/img/oracle-doc-logo.png
    name: coherence-operator
    sources:
    - https://github.com/oracle/coherence-operator
    urls:
    - https://oracle.github.io/coherence-operator/charts/coherence-operator-0.9.9.tgz
    version: 0.9.9
  - apiVersion: v1
    appVersion: 0.9.8
    created: 2019-11-13T05:16:25.823555691Z
    description: A Kubernetes Operator for Coherence
    digest: 73db005ae718dc51b85fa57748f70f0381465f12f50f366a80e2aec2bd6cf33f
    home: https://github.com/oracle/coherence-operator
    icon: https://docs.oracle.com/en/dcommon/img/oracle-doc-logo.png
    name: coherence-operator
    sources:
    - https://github.com/oracle/coherence-operator
    urls:
    - https://oracle.github.io/coherence-operator/charts/coherence-operator-0.9.8.tgz
    version: 0.9.8
  - apiVersion: v1
    appVersion: 0.9.7
    created: 2019-11-13T05:16:25.809539098Z
    description: A Kubernetes Operator for Coherence
    digest: ad24a31b6d9e3d0988483743018509501700577c88168087dc9d7612cfe8421c
    home: https://github.com/oracle/coherence-operator
    icon: https://docs.oracle.com/en/dcommon/img/oracle-doc-logo.png
    keywords:
    - operator
    - coherence
    - datagrid
    name: coherence-operator
    sources:
    - https://github.com/oracle/coherence-operator
    urls:
    - https://oracle.github.io/coherence-operator/charts/coherence-operator-0.9.7.tgz
    version: 0.9.7
  - apiVersion: v1
    appVersion: 0.9.6
    created: 2019-11-13T05:16:25.796861765Z
    description: A Kubernetes Operator for Coherence
    digest: c7175044401acdc605bba80ab95be91cbc30575dd96351f6d1c18b419d1171af
    home: https://github.com/oracle/coherence-operator
    icon: https://docs.oracle.com/en/dcommon/img/oracle-doc-logo.png
    keywords:
    - operator
    - coherence
    - datagrid
    name: coherence-operator
    sources:
    - https://github.com/oracle/coherence-operator
    urls:
    - https://oracle.github.io/coherence-operator/charts/coherence-operator-0.9.6.tgz
    version: 0.9.6
  - apiVersion: v1
    appVersion: 0.9.5
    created: 2019-11-13T05:16:25.784292723Z
    description: A Kubernetes Operator for Coherence
    digest: 438edb4ee1b2def3695ce636d44ab0fbdae032555018716768dfc36ea04deec8
    home: https://github.com/oracle/coherence-operator
    icon: https://docs.oracle.com/en/dcommon/img/oracle-doc-logo.png
    keywords:
    - operator
    - coherence
    - datagrid
    name: coherence-operator
    sources:
    - https://github.com/oracle/coherence-operator
    urls:
    - https://oracle.github.io/coherence-operator/charts/coherence-operator-0.9.5.tgz
    version: 0.9.5
  - apiVersion: v1
    appVersion: 0.9.4
    created: 2019-11-13T05:16:25.770845718Z
    description: A Kubernetes Operator for Coherence
    digest: 9696b0cccd098f362313955b25a91aa22465672e9d28b1c577e7f18cb97c3895
    home: https://github.com/oracle/coherence-operator
    icon: https://docs.oracle.com/en/dcommon/img/oracle-doc-logo.png
    keywords:
    - operator
    - coherence
    - datagrid
    name: coherence-operator
    sources:
    - https://github.com/oracle/coherence-operator
    urls:
    - https://oracle.github.io/coherence-operator/charts/coherence-operator-0.9.4.tgz
    version: 0.9.4
  - apiVersion: v1
    appVersion: 0.9.3
    created: 2019-11-13T05:16:25.758052628Z
    description: A Kubernetes Operator for Coherence
    digest: 4ffe57a7f81974baa4ae1cc6d0485747f266d99d1af17e73a283c4b73c6a5b3a
    home: https://github.com/oracle/coherence-operator
    icon: https://docs.oracle.com/en/dcommon/img/oracle-doc-logo.png
    keywords:
    - operator
    - coherence
    - datagrid
    name: coherence-operator
    sources:
    - https://github.com/oracle/coherence-operator
    urls:
    - https://oracle.github.io/coherence-operator/charts/coherence-operator-0.9.3.tgz
    version: 0.9.3
generated: 2019-11-13T05:16:25.714338447Z
