apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  coherence:
    cacheConfig: test-config.xml
  roles:
    - role: data
    - role: proxy
      coherence:
        cacheConfig: proxy-config.xml
