apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  coherence:
    logLevel: 6
  roles:
    - role: data
      coherence:
        logLevel: 9
    - role: proxy
