apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  roles:
    - role: data
      coherence:
        overrideConfig: data-override.xml
    - role: proxy
      coherence:
        overrideConfig: proxy-override.xml
