apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  roles:
    - role: data
      coherence:
        persistence:
          enabled: true
          persistentVolumeClaim:
            storageClassName: foo
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 2Gi
    - role: proxy
      coherence:
        persistence:
          enabled: false
