apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: test-cluster
spec:
  readinessProbe:
    initialDelaySeconds: 10
    periodSeconds: 30
  roles:
  - role: one
    replicas: 1
    coherence:
      image: "test/coherence:1.0"
      cacheConfig: "test-cache-config.xml"
